### PR TITLE
Fixing potential mutext leak.

### LINKED ISSUE #17: Make pausing (via the Alt + Space shortcut) when a sound isn't playing not lock the program
Currently, if you pause when a sound isn't playing, it's impossible to play a new sound effect (with a keyboard shortcut) until you restart the program. Not sure if you can still play sounds via chat during this locking situation (haven't tested).

### PR DESCRIPTION
**Pull request by xuther**
I ran into this as I was testing some stuff. Figured it was better to get it in sooner than later.

### CODE REVIEW

**Comment by xuther** [comment]
@jessemillar for the notification.

**Comment by jessemillar** [comment]
@xuther Been a while since I've dealt with mutexes. What was the issue and how does this fix it? #education

**Comment by xuther** [comment]
Essentially just that the mutex is acquired and then there's a valid (non-shutdown) codepath that returns without unlocking (if the error on line 334 is not nil). So if that error is handled, but the program doesn't exit, subsequent calls to lock the mutex would block forever.

**Comment by jessemillar** [comment]
This actually fixes #17. Awesome!

**Review by jessemillar — APPROVED** [review]

**Comment by jessemillar** [comment]
@xuther Add me on Discord so we can chat in a more longform fashion. `B-Froggio#6354`

**Pull request merged**
